import 'package:g_pay/core/utils/g_pay_image_constant.dart';

import '../core/g_pay_export.dart';

/// Helper class for managing themes and colors.
class ThemeManager {
  static String _themeData = 'primary';

  static void setThemeData(String theme) {
    _themeData = theme;
  }

  static String getThemeData() {
    return _themeData;
  }
}

class ThemeHelper {
  // The current app theme
  final _appTheme = ThemeManager.getThemeData();

// A map of custom color themes supported by the app
  final Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  final Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generatorif (!_supportedCustomColor.containsKey(_appTheme)){  throw Exception(               "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");      } //return theme from map
    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator if (!_supportedColorScheme.containsKey(_appTheme)){   throw Exception(                "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");       }  //return theme from map
    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: colorScheme.primaryContainer,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
            backgroundColor: colorScheme.onError.withOpacity(0.36),
            shape:
                RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
            shadowColor: colorScheme.primary,
            elevation: 4,
            visualDensity: const VisualDensity(
              vertical: -4,
              horizontal: -4,
            ),
            padding: EdgeInsets.zero),
      ),
      dividerTheme: DividerThemeData(
          thickness: 24, space: 24, color: colorScheme.onPrimaryContainer),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        displaySmall: GoogleFonts.manrope(
            color: colorScheme.onPrimaryContainer,
            fontSize: 35.0,
            fontWeight: FontWeight.w700,
            shadows: [
              const Shadow(
                  color: Colors.black54, offset: Offset(2, 2), blurRadius: 3),
            ]),
        titleLarge: GoogleFonts.manrope(
            color: colorScheme.onPrimaryContainer,
            fontSize: 20.0,
            fontWeight: FontWeight.w800,
            shadows: [
              const Shadow(
                  color: Colors.black54, offset: Offset(2, 2), blurRadius: 3),
            ]),
        titleMedium: GoogleFonts.manrope(
            color: colorScheme.onPrimaryContainer,
            fontSize: 18.0,
            fontWeight: FontWeight.w500,
            shadows: [
              const Shadow(
                  color: Colors.black54, offset: Offset(2, 2), blurRadius: 3),
            ]),
        titleSmall: GoogleFonts.manrope(
            color: Colors.grey[800],
            fontSize: 18.0,
            fontWeight: FontWeight.w500,
            shadows: [
              const Shadow(
                  color: Colors.black, offset: Offset(0, 0), blurRadius: 1),
            ]),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static const primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0X3F000000),
    primaryContainer: Color(0XFF202020),

    // Error colors
    errorContainer: Color(0XFF949494),
    onError: Color(0XFFFFFFFF),

    // On colors(text colors)
    onPrimary: Color(0X44313131),
    onPrimaryContainer: Color(0XFFDEDEDE),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Olive
  Color get olive => const Color(0XFFF7F3D7);

  // White
  Color get white => const Color(0XFFFFFFFF);

  // Brown
  Color get brown200 => const Color(0XFF937131);
}

class GPayDecoration {
  static BoxDecoration get normalDecoration =>
      const BoxDecoration(color: Colors.transparent);

  static BoxDecoration get appBarDecoration => BoxDecoration(
    color: theme.colorScheme.onPrimary,
    image: DecorationImage(
        image: AssetImage(GPayImageConstant.imagePath),
        fit: BoxFit.cover),
  );

}

class BorderRadiusStyle {
  static BorderRadius get roundedBorder5 => BorderRadius.circular(5.0);
}

double get strokeAlignInside => BorderSide.strokeAlignInside;

double get strokeAlignCenter => BorderSide.strokeAlignCenter;

double get strokeAlignOutside => BorderSide.strokeAlignOutside;

class GPayTextStyles {
  // Display text style
  static get displaySmall =>
      theme.textTheme.displaySmall!.copyWith(fontSize: 30.0, height: 1.35);
  static get titleMediumSemiBold =>
      theme.textTheme.titleMedium!.copyWith(fontWeight: FontWeight.w600);
}

class GPayButtonStyles {
  // Text button style
  static ButtonStyle get none => ButtonStyle(
      backgroundColor: MaterialStateProperty.all<Color>(Colors.transparent),
      elevation: MaterialStateProperty.all<double>(0));

  static ButtonStyle get elevatedButtonDecoration => ButtonStyle(
      backgroundColor: MaterialStateProperty.all<Color>(Colors.transparent),
      elevation: MaterialStateProperty.all<double>(0));
}

/// Class containing custom colors for a primary theme.
PrimaryColors get appTheme => ThemeHelper().themeColor();

ThemeData get theme => ThemeHelper().themeData();
